### ISSUE TITLE
Hostname

### ISSUE THREAD

**Issue by schultyy** [schultyy/Sokan#5]
A user is able to set a host name in the configuration.

``` yaml
srv01:
  - packages:
  - files:
```

If no host name is provided, it defaults to 'default' in the configuration. Then the machine doesn't get any specific name.
